#!/bin/sh

# PROVIDE: shutserverd
# REQUIRE: NETWORKING inetd jail cron sshd syscons
# KEYWORD: 

. /etc/rc.subr

name="shutserverd"
rcvar=`set_rcvar`
pidfile="/var/run/$name.pid"
command="/home/chai/bin/$name.py"
start_cmd="ss_start"
stop_cmd=":"

ss_start() {
  echo "$name starting..."
  $command
}

load_rc_config $name
run_rc_command "$1" 
